title: Susan # your name (or website title) here
logo: "/images/IMG_20200702_130601.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Samples of code for geolocation data 
  <br><br>
  <a href="https://www.linkedin.com/in/sualjohn/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
